server:
  servlet:
    context-path: /api/v1.0.0/inventory-service

  port: 9494

application:
  cors:
    origins: http://localhost:4200,http://localhost:8080


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      hibernate:
        type: trace
        SQL: debug