name: CONFIG SERVER CI

on:
  push:
    branches:
      - main
    paths:
      - 'CONFIG-SERVER/**'
      - 'docker/backend/config-service/**'
      - 'docker-compose.yml'
      - '.github/workflows/config-server-*.yml'

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Setup Environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java Environment
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2  # Cache Maven dependencies
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

  compile:
    runs-on: ubuntu-latest
    needs: setup
    name: Compile Project
    steps:
      - name: Compile project
        run: mvn compile

  unit-tests:
    runs-on: ubuntu-latest
    needs: compile
    name: Run Unit Tests
    steps:
      - name: Run unit tests
        run: mvn test

  build:
    runs-on: ubuntu-latest
    needs: unit-tests
    name: Build Project
    steps:
      - name: Build project
        run: mvn package -DskipTests

  build-image:
    runs-on: ubuntu-latest
    needs: build
    name: Build & Push Docker Image
    steps:
      - name: Extract Version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: your-docker-hub-username/config-server:${{ env.VERSION }}, your-docker-hub-username/config-server:latest
